[package]
name = "svgtoemf"
authors = ["fliedonion"]
description = "Inkscape wrapper to convert svg to emf. Rust version."
version = "0.9.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

